version: "3.4"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ./vpn:/vpn # OpenVPN configuration
    dns:
      - 8.8.8.8
      - 4.4.4.4
    security_opt:
      - label:disable
    ports:
      - "11470:11470"
      - "12470:12470"
    # command: "-r 192.168.1.0/24" # route local network traffic # 172.17.0.1/16
  
  stremio-server:
    container_name: stremio-server
    build: .
    restart: "unless-stopped"
    depends_on:
      - vpn
    network_mode: service:vpn # run on the vpn network